// Source for src/layouts/index.ts, which the save endpoint regenerates
// whenever a layout is created or deleted. A plain module (not a Vite glob)
// so core code and tests under tsx can read the library too.
import { isLayoutId } from './schema.ts';

export function renderLayoutIndex(ids: string[]): string {
  const sorted = ids.filter(isLayoutId).sort(),
    ident = (id: string) => `layout_${id.replace(/-/g, '_')}`;
  return [
    '// Generated by the controller designer (see src/controls/layout/index-file.ts).',
    '// Lists every layout in this folder; do not edit by hand.',
    "import { asControllerLayout, type ControllerLayout } from '../controls/layout/schema.ts';",
    ...sorted.map(
      (id) => `import ${ident(id)} from './${id}.json' with { type: 'json' };`,
    ),
    '',
    'export const layouts: Record<string, ControllerLayout> = {',
    ...sorted.map((id) => `  '${id}': asControllerLayout(${ident(id)}),`),
    '};',
    '',
  ].join('\n');
}
